### ISSUE TITLE
re-frame-debux not working

### ISSUE THREAD

**Issue by liaowang11** [jacekschae/conduit#14]
Steps to reproduce:
1. clone the repo
2. `yarn install`
3. `yarn dev`
4. `shadow-cljs` gives this log: duplicate resource day8/re_frame/tracing.cljc on classpath, using jar:file:$HOME/.m2/repository/day8/re-frame/tracing-stubs/0.5.1/tracing-stubs-0.5.1.jar!/day8/re_frame/tracing.cljc over jar:file:/$HOME/.m2/repository/day8/re-frame/tracing/0.5.1/tracing-0.5.1.jar!/day8/re_frame/tracing.cljc

Expected:
Function Trace enabled by default

Actual:
Function Trace not enabled

Fix:
Commenting out `tracing-stubs` fixes this, but I don't think it's a good idea.
```clojure
                 ;; [day8.re-frame/tracing-stubs "0.5.1"]
```

**Comment by jacekschae** [comment]
Sorry for taking so long regarding this. I just updated the config and it should work without a problem.
