### ISSUE TITLE
Optimize output

### ISSUE THREAD

**Issue by thheller** [jacekschae/conduit#15]
I was just looking over this repo and noticed that the final JS file is way too big.

I recommend generating a build report but the offenders that shouldn't be included are `cljs.pprint` and `cljs.analyzer`. Don't know who is responsible for including those but my guess is on the re-frame tracing stuff.

Try
```bash
$ shadow-cljs run shadow.cljs.build-report app report.html
# then open report.html
```

![reframe-conduit](https://user-images.githubusercontent.com/144930/57199408-dc0e5500-6f7e-11e9-898a-d75f1eb93f69.jpg)

**Comment by jacekschae** [comment]
Do you think we can trim this any further?
<img width="812" alt="Screen Shot 2020-03-04 at 21 36 26" src="https://user-images.githubusercontent.com/31179812/75920869-791c7180-5e60-11ea-9ec6-6d6af189e226.png">

**Comment by thheller** [comment]
Very small tweak via `:compiler-options {:shadow-keywords true}` maybe. Looks fine otherwise.

**Comment by jacekschae** [comment]
It reduced by 4KB, also removed cljs-time

<img width="811" alt="Screen Shot 2020-03-04 at 22 01 43" src="https://user-images.githubusercontent.com/31179812/75922705-d665f200-5e63-11ea-9a2c-64beac674030.png">

**Comment by jacekschae** [comment]
Thanks!

**Comment by thheller** [comment]
Can you push the latest code? I'd like to test something.
