### ISSUE TITLE
Broken Live-Reload

### ISSUE THREAD

**Issue by thheller** [jacekschae/conduit#4]
Live-Reload is broken due to the repeated calls of `hook-browser-navigation!`. The `goog.History` instance can only be constructed once as it will wipe the DOM completely if constructed a second time after the page has finished loading.

It could be changed to a `defonce` instead and just removing the `hook-browser-navigation!` call.

```
(defonce history
  (doto (History.)
    (gevents/listen
      EventType/NAVIGATE
      (fn [event]
        (secretary/dispatch! (.-token event))))
    (.setEnabled true)))
```

**Comment by jacekschae** [comment]
Thanks @thheller just change that
