### ISSUE TITLE
"No config for build app; found" (npm run script error)

### ISSUE THREAD

**Issue by robjens** [jacekschae/conduit#5]
Minor thing I encountered but on my Windows machine (Git Bash MinGW), following README instructions failed. It appears that the end-of-string semicolons at `package.json` scripts key are causing problems.

https://github.com/jacekschae/conduit/blob/41c627dd7c646b8879d063622e4fb823f7d85cae/package.json#L15-L17

```
shadow-cljs - starting ...
No config for build "app;" found.
Available builds are: npm, app
Done in 60.56s.
```
Simply removing them will make it work. Guess this doesn't happen on a true nix* (or OSX for that matter) as others, including author, would likely to have caught it. I figure removing them wouldn't harm either though ...

**Comment by jacekschae** [comment]
Hi @robjens,

Thanks for reporting this. Just fixed it. Also added clean for windows users.
