### ISSUE TITLE
Problems with building production

### ISSUE THREAD

**Issue by jacekschae** [jacekschae/conduit#6]
I spend better part of this weekend to swap the router and refactor few thigs. Everyting seems to be working pretty well in dev. When I run `yarn release` it builds but when i put it in production it says:

```
ReferenceError: conduit is not defined
<script>window.onload = function() { conduit.core.main(); }</script>
```

Which is pretty obv but still can't figure it out ... . I think this might be a silly mistake on my side ...

Deployed version with errror: https://jacekschae.github.io/conduit-re-frame-demo/

Any ideas @thheller?

**Comment by thheller** [comment]
I get a 404 for https://jacekschae.github.io/js/main.js?
